improve messages, check, consistents options between scripts

diff --git a/backup_pitr b/backup_pitr
--- a/backup_pitr
+++ b/backup_pitr
@@ -25,6 +25,15 @@ usage() {
     exit $1
 }
 
+error() {
+    echo "ERROR: $*" 1>&2
+    exit 1
+}
+
+info() {
+    echo "INFO: $*"
+}
+
 # Hard coded configuration
 local_backup="no"
 backup_root=/var/lib/pgsql/backups
@@ -61,7 +70,7 @@ done
 target=$1
 # Destination host is mandatory unless the backup is local
 if [ -z "$target" ] && [ $local_backup != "yes" ]; then
-    echo "ERROR: missing target host" 1>&2
+    echo -e "FATAL: missing target host\n" 1>&2
     usage 1
 fi
 
@@ -82,10 +91,10 @@ stop_backup() {
     trap '' INT TERM EXIT
 
     # Tell PostgreSQL the backup is done
+    info "stopping the backup process"
     $psql_command -Atc "SELECT pg_stop_backup();" $psql_condb >/dev/null
     if [ $? != 0 ]; then
-	echo "ERROR: could not stop backup process" 1>&2
-        exit 1
+	error "could not stop backup process"
     fi
 
     # Reset the signal handler, this function should only be called once
@@ -94,50 +103,49 @@ stop_backup() {
 
 # Prepare target directoties
 backup_dir=$backup_root/${label_prefix}/${current_time}
+info "backup directory is $backup_dir"
+info "preparing directories"
+
 if [ $local_backup = "yes" ]; then
     mkdir -p $backup_dir
     if [ $? != 0 ]; then
-	echo "ERROR: could not create $backup_dir" 1>&2
-	exit 1
+	error "could not create $backup_dir"
     fi
 	
     mkdir -p $backup_dir/tblspc
     if [ $? != 0 ]; then
-	echo "ERROR: could not create $backup_dir/tblspc" 1>&2
-	exit 1
+	error "could not create $backup_dir/tblspc"
     fi
 
 else
     ssh $target "mkdir -p $backup_dir"
     if [ $? != 0 ]; then
-	echo "ERROR: could not create $backup_dir" 1>&2
-	exit 1
+	error "could not create $backup_dir"
     fi
 
     ssh $target "mkdir -p $backup_dir/tblspc"
     if [ $? != 0 ]; then
-	echo "ERROR: could not create $backup_dir/tblspc" 1>&2
-	exit 1
+	error "could not create $backup_dir/tblspc"
     fi
 
 fi
 
 # Start the backup
+info "starting the backup process"
 start_backup_xlog=`$psql_command -Atc "SELECT pg_xlogfile_name(pg_start_backup('${label_prefix}_${current_time}'));" $psql_condb`
 if [ $? != 0 ]; then
-    echo "ERROR: could not start backup process" 1>&2
-    exit 1
+    error "could not start backup process"
 fi
 
 # Add a signal handler to avoid leaving the cluster in backup mode when exiting on error
 trap stop_backup INT TERM KILL EXIT
 
 # Tar $PGDATA
+info "archiving PGDATA: $pgdata"
 was=`pwd`
 cd $pgdata
 if [ $? != 0 ]; then
-    echo "ERROR: could not change current directory to $pgdata" 1>&2
-    exit 1
+    error "could not change current directory to $pgdata"
 fi
 
 if [ $local_backup = "yes" ]; then
@@ -146,8 +154,7 @@ if [ $local_backup = "yes" ]; then
     tar_rc=${rc[0]}
     gzip_rc=${rc[1]}
     if [ $tar_rc = 2 ] || [ $gzip_rc != 0 ]; then
-	echo "ERROR: could not tar PGDATA" 1>&2
-	exit 1
+	error "could not tar PGDATA"
     fi
 else
     tar -cpf - --ignore-failed-read --exclude=pg_xlog --exclude='postmaster.*' * 2>/dev/null | gzip | ssh $target "cat > $backup_dir/pgdata.tar.gz"
@@ -156,29 +163,36 @@ else
     gzip_rc=${rc[1]}
     ssh_rc=${rc[2]}
     if [ $tar_rc = 2 ] || [ $gzip_rc != 0 ] || [ $ssh_rc != 0 ]; then
-	echo "ERROR: could not tar PGDATA" 1>&2
-	exit 1
+	error "could not tar PGDATA"
     fi
 fi
 cd $was
 
 # Tar the tablespaces.  The list comes from PostgreSQL to be sure to tar only
 # defined tablespaces.
+info "listing tablespaces"
 tblspc_list=`mktemp -t backup_pitr.XXXXXX`
 $psql_command -Atc "SELECT spcname,spclocation,oid FROM pg_tablespace WHERE spcname NOT IN ('pg_default', 'pg_global') AND spclocation <> '';" $psql_condb | tr ' ' '_' > $tblspc_list
+rc=(${PIPESTATUS[*]})
+psql_rc=${rc[0]}
+tr_rc=${rc[1]}
+if [ $psql_rc != 0 ] || [ $tr_rc != 0 ]; then
+    error "could not get the list of tablespaces from PostgreSQL"
+fi
 
 for line in `cat $tblspc_list`; do
 
     name=`echo $line | cut -d '|' -f 1`
     location=`echo $line | cut -d '|' -f 2`
 
+    info "archiving tablespace \"$name\" ($location)"
+
     # Change directory to the parent directory or the tablespace to be
     # able to tar only the base directory
     was=`pwd`
     cd $location
     if [ $? != 0 ]; then
-	echo "ERROR: could not change current directory to $location" 1>&2
-	exit 1
+	error "could not change current directory to $location"
     fi
 
     # Tar the directory, directly to the remote location if needed.  The name
@@ -190,8 +204,7 @@ for line in `cat $tblspc_list`; do
 	tar_rc=${rc[0]}
 	gzip_rc=${rc[1]}
 	if [ $tar_rc = 2 ] || [ $gzip_rc != 0 ]; then
-	    echo "ERROR: could not tar tablespace $name" 1>&2
-	    exit 1
+	    error "could not tar tablespace $name"
 	fi
     else
 	tar -cpf - --ignore-failed-read * 2>/dev/null | gzip | ssh $target "cat > $backup_dir/tblspc/${name}.tar.gz"
@@ -200,8 +213,7 @@ for line in `cat $tblspc_list`; do
 	gzip_rc=${rc[1]}
 	ssh_rc=${rc[2]}
 	if [ $tar_rc = 2 ] || [ $gzip_rc != 0 ] || [ $ssh_rc != 0 ]; then
-	    echo "ERROR: could not tar tablespace $name" 1>&2
-	    exit 1
+	    error "could not tar tablespace $name"
 	fi
     fi
 
@@ -213,36 +225,38 @@ stop_backup
 
 if [ $local_backup = "yes" ]; then
     # Copy the backup history file
+    info "copying the backup history file"
     cp $pgdata/pg_xlog/${start_backup_xlog}.*.backup $backup_dir/backup_label
     if [ $? != 0 ]; then
-	echo "ERROR: could not copy backup history file to $backup_dir" 1>&2
-	exit 1
+	error "could not copy backup history file to $backup_dir"
     fi
 
     # Add the name and location of the tablespace to an helper file for
     # the restoration script
+    info "copying the tablespaces list"
     cp $tblspc_list $backup_dir/tblspc_list
     if [ $? != 0 ]; then
-	echo "ERROR: could not copy the tablespace list to $backup_dir" 1>&2
-	exit 1
+	error "could not copy the tablespace list to $backup_dir"
     fi
 else
     echo $target | grep -q ':' && target="[${target}]"
     # Copy the backup history file
+    info "copying the backup history file"
     scp $pgdata/pg_xlog/${start_backup_xlog}.*.backup ${target}:$backup_dir/backup_label > /dev/null
     if [ $? != 0 ]; then
-	echo "ERROR: could not copy backup history file to ${target}:$backup_dir" 1>&2
-	exit 1
+	error "could not copy backup history file to ${target}:$backup_dir"
     fi
 
     # Add the name and location of the tablespace to an helper file for
     # the restoration script
+    info "copying the tablespaces list"
     scp $tblspc_list ${target}:$backup_dir/tblspc_list >/dev/null
     if [ $? != 0 ]; then
-	echo "ERROR: could not copy the tablespace list to ${target}:$backup_dir" 1>&2
-	exit 1
+	error "could not copy the tablespace list to ${target}:$backup_dir"
     fi
 fi
 
 # Cleanup
 rm $tblspc_list
+
+info "done"
diff --git a/purge_pitr b/purge_pitr
--- a/purge_pitr
+++ b/purge_pitr
@@ -8,12 +8,12 @@ usage() {
     echo "    -l label     Label to process"
     echo "    -b dir       Backup directory"
     echo "    -n host      Host storing archived WALs"
-    echo "    -x dir       Archived WALs directory"
+    echo "    -X dir       Archived WALs directory"
     echo
     echo "    -m count     Keep this number of backups"
     echo "    -d days      Purge backup older than this number of days"
     echo
-    echo "    -h           Print help"
+    echo "    -?           Print help"
     echo
     exit $1
 }
@@ -25,9 +25,17 @@ label_prefix="replitr"
 local_xlog="no"
 xlog_dir=/var/lib/pgsql/archived_xlog
 
+info() {
+    echo "INFO: $*"
+}
+
+error() {
+    echo "ERROR: $*" 1>&2
+    exit 1
+}
 
 # CLI options
-args=`getopt "Ll:b:n:x:m:d:h" $*`
+args=`getopt "Ll:b:n:X:m:d:?" $*`
 if [ $? -ne 0 ]
 then
     usage 2
@@ -41,11 +49,11 @@ do
 	-l) label_prefix=$2; shift 2;;
 	-b) backup_root=$2; shift 2;;
 	-n) xlog_host=$2; shift 2;;
-	-x) xlog_dir=$2; shift 2;;
+	-X) xlog_dir=$2; shift 2;;
 	-m) max_count=$2; shift 2;;
 	-d) max_days=$2; shift 2;;
 
-        -h) usage 1;;
+        -\?) usage 1;;
         --) shift; break;;
     esac
 done
@@ -105,25 +113,39 @@ if [ -n "$max_count" ]; then
     if [ -n "$remove_list" ]; then
 	for dir in $remove_list; do
 	    if [ $local_backup = "yes" ]; then
+		info "purging $dir"
 		rm -rf $dir
-		# XXX tell the user these is a failure and continue
+		if [ $? != 0 ]; then
+		    echo "WARNING: Unable to remove $dir" 1>&2
+		fi
 	    else
+		info "purging $dir"
 		ssh $target "rm -rf $dir"
+		if [ $? != 0 ]; then
+		    echo "WARNING: Unable to remove $target:$dir" 1>&2
+		fi
 	    fi
 	done
     fi
 else
     if [ -n "$max_days" ]; then
 	# Find the limiting date from now and the specified number of days
-	ldate=`date --date="-5 day" +%Y%m%d%H%M%S`
+	ldate=`date --date="-$max_days day" +%Y%m%d%H%M%S`
 	for dir in $list; do
-	    bdate=`basename $dir | sed -e 's/[^0-9]//g`
+	    bdate=`basename $dir | sed -e 's/[^0-9]//g'`
 	    if [ $ldate -gt $bdate ]; then
 		if [ $local_backup = "yes" ]; then
+		    info "purging $dir"
 		    rm -rf $dir
-		    # XXX tell the user these is a failure and continue
+		    if [ $? != 0 ]; then
+			echo "WARNING: Unable to remove $dir" 1>&2
+		    fi
 		else
+		    info "purging $dir"
 		    ssh $target "rm -rf $dir"
+		    if [ $? != 0 ]; then
+			echo "WARNING: Unable to remove $target:$dir" 1>&2
+		    fi
 		fi
 	    fi
 	done
@@ -169,6 +191,8 @@ fi
 wal_file=`grep '^START WAL LOCATION' $backup_label | cut -d' ' -f 6 | sed -e 's/[^0-9A-F]//g'`
 max_wal_num=$((16#$wal_file))
 
+info "purging WAL files older than `basename $wal_file .gz`"
+
 # List the WAL files and remove the old ones based on their name
 # which are ordered in time by their naming scheme
 if [ $local_xlog = "yes" ]; then
@@ -179,12 +203,16 @@ if [ $local_xlog = "yes" ]; then
     fi
     for wal in $wal_list; do
 	w=`basename $wal .gz`
-	# Exclude history and backup label files
+	# Exclude history and backup label files from the listing
 	echo $w | grep -q '\.'
 	if [ $? != 0 ]; then
 	    wal_num=$(( 16#$w ))
 	    if [ $wal_num -lt $max_wal_num ]; then
+		# Remove the WAL file and possible the backup history file
 		rm $xlog_dir/$w*.gz
+		if [ $? != 0 ]; then
+		    echo "WARNING: Unable to remove $w" 1>&2
+		fi
 	    fi
 	fi
     done
@@ -202,6 +230,9 @@ else
 	    wal_num=$(( 16#$w ))
 	    if [ $wal_num -lt $max_wal_num ]; then
 		ssh $xlog_host "rm $xlog_dir/$w*.gz"
+		if [ $? != 0 ]; then
+		    echo "WARNING: Unable to remove $w on $xlog_host" 1>&2
+		fi
 	    fi
 	fi
     done
@@ -211,3 +242,5 @@ fi
 if [ -d "$tmp_dir" ]; then
     rm -rf $tmp_dir
 fi
+
+info "done"
diff --git a/restore_pitr b/restore_pitr
--- a/restore_pitr
+++ b/restore_pitr
@@ -30,73 +30,81 @@ usage() {
     exit $1
 }
 
+error() {
+    echo "ERROR: $*" 1>&2
+    exit 1
+}
+
+info() {
+    echo "INFO: $*"
+}
+
 check_and_fix_directory() {
     [ $# = 1 ] || return 1
     local dir=$1
 
     # Check if directory exists
     if [ ! -d "$dir" ]; then
+	info "creating $dir"
 	mkdir -p $dir
 	if [ $? != 0 ]; then
-	    echo "ERROR: could not create $dir" 1>&2
-	    exit 1
+	    error "could not create $dir"
 	fi
+	info "setting permissions of $dir"
 	chmod 700 $dir
 
 	# Change owner of directory only if run as root
 	if [ `id -u` = 0 ]; then
+	    info "setting owner of $dir"
 	    chown ${owner}: $dir
 	    if [ $? != 0 ]; then
-		echo "ERROR: could not change owner of $dir to $owner" 1>&2
-		exit 1
+		error "could not change owner of $dir to $owner"
 	    fi
 	fi
     fi
 
     # Check if directory is empty
+    info "checking if $dir is empty"
     ls $dir >/dev/null 2>&1
     ls_rc=$?
     content=`ls $dir 2>/dev/null | wc -l`
     wc_rc=$?
     if [ $ls_rc != 0 ] || [ $wc_rc != 0 ]; then
-	echo "ERROR: could not check if $dir is empty" 1>&2
-	exit 1
+	error "could not check if $dir is empty"
     fi
 
     if [ $content != 0 ]; then
 	# XXX add a switch to force
-	echo "ERROR: $dir is not empty. Contents won't be overridden" 1>&2
-	exit 1
+	error "$dir is not empty. Contents won't be overridden"
     fi
     
     # Check owner
     downer=`stat -c %U $dir 2>/dev/null`
     if [ $? != 0 ]; then
-	echo "ERROR: Unable to get owner of $dir" 1>&2
+	error "Unable to get owner of $dir"
 	exit 1
     fi
 
     if [ $downer != $owner ]; then
 	if [ `id -u` = 0 ]; then
+	    info "setting owner of $dir"
 	    chown ${owner}: $dir
 	    if [ $? != 0 ]; then
-		echo "ERROR: could not change owner of $dir to $owner" 1>&2
-		exit 1
+		error "could not change owner of $dir to $owner"
 	    fi
 	else
-	    echo "ERROR: $dir must be owned by $owner" 1>&2
-	    exit 1
+	    error "$dir must be owned by $owner"
 	fi
     fi
 
     # Check permissions
     dperms=`stat -c %a $dir 2>/dev/null`
     if [ $? != 0 ]; then
-	echo "ERROR: Unable to get permissions of $dir" 1>&2
-	exit 1
+	error "Unable to get permissions of $dir"
     fi
 
     if [ $dperms != "700" ]; then
+	info "setting permissions of $dir"
 	chmod 700 $dir
     fi
 
@@ -116,23 +124,26 @@ while getopts "Lb:l:D:X:d:O:r:?" opt; do
 	O) owner=$OPTARG;;
 	r) restore_prog=$OPTARG;;
 	"?") usage 1;;
-	*) echo "Unknown error while processing options" 1>&2; exit 1;;
+	*) error "Unknown error while processing options";;
     esac
 done
-set -- "${@:$OPTIND}"
+#set -- "${@:$OPTIND}"
 
-source=$1
+source=${@:$OPTIND:1}
 
 # Storage host is mandatory unless stored locally
 if [ -z "$source" ] && [ $local_backup != "yes" ]; then
-    echo "ERROR: missing target host" 1>&2
+    echo "FATAL: missing target host" 1>&2
     usage 1
 fi
 
 # XXX check input date
 
 # find the backup according to given date: $backup_dir
+info "searching backup directory"
 if [ -n "$target_date" ]; then
+    info "target date is: $target_date"
+
     # date format is numerically ordered
     tdate=`echo $target_date | sed -e 's/[^0-9]//g'`
 
@@ -140,14 +151,12 @@ if [ -n "$target_date" ]; then
     if [ $local_backup = "yes" ]; then
 	list=`ls -d $backup_root/$label_prefix/[0-9]* 2>/dev/null`
 	if [ $? != 0 ]; then
-	    echo "ERROR: could not list the content of $backup_root/$label_prefix/" 1>&2
-	    exit 1
+	    error "could not list the content of $backup_root/$label_prefix/"
 	fi
     else
 	list=`ssh $source "ls -d $backup_root/$label_prefix/[0-9]*" 2>/dev/null`
 	if [ $? != 0 ]; then
-	    echo "ERROR: could not list the content of $backup_root/$label_prefix/ on $source" 1>&2
-	    exit 1
+	    error "could not list the content of $backup_root/$label_prefix/ on $source"
 	fi
     fi
 
@@ -163,35 +172,31 @@ if [ -n "$target_date" ]; then
     done
 
     if [ -z "$backup_date" ]; then
-	echo "ERROR: Could not find a backup at given date $target_date" 1>&2
-	exit 1
+	error "Could not find a backup at given date $target_date"
     fi
 else
     # get the latest
     if [ $local_backup = "yes" ]; then
 	backup_date=`ls -d $backup_root/$label_prefix/[0-9]* 2>/dev/null | tail -1`
 	if [ $? != 0 ]; then
-	    echo "ERROR: could not list the content of $backup_root/$label_prefix/" 1>&2
-	    exit 1
+	    error "could not list the content of $backup_root/$label_prefix/"
 	fi
     else
 	backup_date=`ssh $source "ls -d $backup_root/$label_prefix/[0-9]*" 2>/dev/null | tail -1`
 	if [ $? != 0 ]; then
-	    echo "ERROR: could not list the content of $backup_root/$label_prefix/ on $source" 1>&2
-	    exit 1
+	    error "could not list the content of $backup_root/$label_prefix/ on $source"
 	fi
     fi
 
     backup_date=`basename $backup_date`
     if [ -z "$backup_date" ]; then
-	echo "ERROR: Could not find a backup" 1>&2
-	exit 1
+	error "Could not find a backup"
     fi
 fi
 
 backup_dir=$backup_root/$label_prefix/$backup_date
 
-echo $backup_dir
+info "backup directory is $backup_dir"
 
 # Check target directories
 # get the tablespace list and check the directories
@@ -204,13 +209,11 @@ else
     if [ $? = 0 ]; then
 	tmp_dir=`mktemp -d -t pg_replitr.XXXXXXXXXX`
 	if [ $? != 0 ]; then
-	    echo "ERROR: could not create temporary directory" 1>&2
-	    exit 1
+	    error "could not create temporary directory"
 	fi
 	scp $source:$backup_dir/tblspc_list $tmp_dir >/dev/null 2>&1
 	if [ $? != 0 ]; then
-	    echo "ERROR: could not copy the list of tablespaces from backup store" 1>&2
-	    exit 1
+	    error "could not copy the list of tablespaces from backup store"
 	fi
 	tblspc_list=$tmp_dir/tblspc_list
     fi
@@ -233,6 +236,7 @@ check_and_fix_directory $pgdata
 
 # Extract everything
 # pgdata
+info "extracting PGDATA to $pgdata"
 was=`pwd`
 cd $pgdata
 if [ $local_backup = "yes" ]; then
@@ -256,10 +260,11 @@ fi
 cd $was
 
 # tablespaces
-[ -n "$tblspc_list" ] && cat $tblspc_list | while read l; do
+[ -n "$tblspc_list" ] && for l in `cat $tblspc_list`; do
     name=`echo $l | cut -d '|' -f 1`
     tbldir=`echo $l | cut -d '|' -f 2`
 
+    info "extracting tablespace \"${name}\" to $tbldir"
     was=`pwd`
     cd $tbldir
     if [ $local_backup = "yes" ]; then
@@ -284,25 +289,23 @@ cd $was
 done
 
 # Create pg_xlog directory if needed
-if [ ! -d $pgdata/pg_xlog ]; then
+if [ ! -d $pgdata/pg_xlog/archive_status ]; then
+    info "preparing pg_xlog directory"
     mkdir -p $pgdata/pg_xlog/archive_status
     if [ $? != 0 ]; then
-	echo "ERROR: could not create $pgdata/pg_xlog" 1>&2
-	exit 1
+	error "could not create $pgdata/pg_xlog"
     fi
 
     if [ `id -u` = 0 ]; then
 	chown -R ${owner}: $pgdata/pg_xlog
 	if [ $? != 0 ]; then
-	    echo "ERROR: could not change owner of $dir to $owner" 1>&2
-	    exit 1
+	    error "could not change owner of $dir to $owner"
 	fi
     fi
 fi
 
 # Create a recovery.conf file in $PGDATA
-#restore_command = 'cp /mnt/server/archivedir/%f %p'
-#recovery_target_time = '2004-07-14 22:39:00 EST'
+info "preparing recovery.conf file"
 prog=`basename $restore_prog`
 if [ $prog = "restore_xlog" ]; then
     if [ $local_backup = "yes" ]; then
@@ -320,3 +323,6 @@ fi
 if [ -n "$tmpdir" ]; then
     rm -rf $tmpdir
 fi
+
+info "done"
+info "please check directories and recovery.conf before starting the cluster"
