[check] save the WAL segment size at backup time and use it before uncompressing

diff --git a/pitrery b/pitrery
--- a/pitrery
+++ b/pitrery
@@ -1919,6 +1919,17 @@ case $action in
             die_and_hook "Failed to get STOP TIME from '$backup_file'"
         fi
 
+        # Starting from 11, the size of WAL segment can be configured
+        # when running initdb, we need to ask PostgreSQL what is the
+        # size of a segment to make the check action work, keeping the
+        # size of a segment in the backup is an optimisation so that
+        # we do not have to uncompress a WAL file to find out its
+        # size.
+        if (( $pg_version >= 110000 )); then
+            wal_segsize=$(${psql_command[@]} -Atc "SELECT setting FROM pg_settings WHERE name = 'wal_segment_size'" $psql_conndb) ||
+                warn "could not get the size of a WAL segment from PostgreSQL"
+        fi
+
         # Ask PostgreSQL where are its configuration file. When they are
         # outside PGDATA, copy them in the backup
         _pgdata=`readlink -f -- "$PGDATA"`
@@ -2018,6 +2029,11 @@ case $action in
 	        echo "$timestamp" > "$backup_dir/backup_timestamp" || warn "could not save timestamp"
             fi
 
+            # Save the size of a WAL segment for latter check actions
+            if [ -n "$wal_segsize" ]; then
+                echo "$wal_segsize" > "$backup_dir/wal_segsize" || warn "could not save WAL segment size"
+            fi
+
             # Add the name and location of the tablespace to an helper file for
             # the restoration script
             info "copying the tablespaces list"
@@ -2073,6 +2089,12 @@ case $action in
             if [ -n "$timestamp" ]; then
 	        ssh -n -- "$backup_ssh_target" "echo '$timestamp' > $(qw "$backup_dir/backup_timestamp")" 2>/dev/null ||
 	            warn "could not save timestamp"
+            fi
+
+            # Save the size of a WAL segment for latter check actions
+            if [ -n "$wal_segsize" ]; then
+                ssh -n -- "$backup_ssh_target" "echo '$wal_segsize' > $(qw "$backup_dir/wal_segsize")" 2>/dev/null ||
+                    warn "could not save WAL segment size"
             fi
 
             # Copy the backup history file
@@ -3740,44 +3762,55 @@ case $action in
                     max_seg=255
                 else
                     # Starting from 11, the WAL segment size can be
-                    # configured at cluster creation, using --wal-segsize
-                    # of initdb.
+                    # configured at cluster creation, using
+                    # --wal-segsize of initdb.  This means we have to
+                    # find the size of a segment to compute the
+                    # maximum number of segments per log.
 
-                    # This means we have to find the size of a segment
-                    # to compute the maximum number of segments per
-                    # log. We take the first segment, uncompress it
+                    # First we check if the wal_segsize exists and
+                    # contains the size of the segments. When it
+                    # fails, we take the first segment, uncompress it
                     # and measure its size
                     [[ "$output" != "nagios" ]] && info "looking for WAL segment size"
-                    for wal_file in "${wal_list[@]}"; do
-                        [[ "$wal_file" =~ .*\.backup.* ]] && continue
-                        first_wal_file="$wal_file"
-                        break
-                    done
 
-                    tmpwal=$(mktemp -t pitr_wal.XXXXXXXXXX) ||
-                        error "Failed to create temporary file"
                     if [ "$backup_local" = "yes" ]; then
-                        if ! cp "$first_wal_file" $tmpwal; then
-                            die "Could not copy archived wal file"
-                        fi
+                        wal_segsize=$(cat "$oldest_dir/wal_segsize" 2>/dev/null)
                     else
-                        if ! scp -- "${archive_ssh_target}:$(qw "$first_wal_file")" $tmpwal >/dev/null 2>&1; then
-                            die "Could not copy archived wal file"
+                        wal_segsize=$(ssh -n -- "$backup_ssh_target" "cat -- $(qw "$oldest_dir/wal_segsize")" 2>/dev/null)
+                    fi
+
+                    if [ -z "$wal_segsize" ]; then
+                        for wal_file in "${wal_list[@]}"; do
+                            [[ "$wal_file" =~ .*\.backup.* ]] && continue
+                            first_wal_file="$wal_file"
+                            break
+                        done
+
+                        tmpwal=$(mktemp -t pitr_wal.XXXXXXXXXX) ||
+                            error "Failed to create temporary file"
+                        if [ "$archive_local" = "yes" ]; then
+                            if ! cp "$first_wal_file" $tmpwal; then
+                                die "Could not copy archived wal file"
+                            fi
+                        else
+                            if ! scp -- "${archive_ssh_target}:$(qw "$first_wal_file")" $tmpwal >/dev/null 2>&1; then
+                                die "Could not copy archived wal file from ${archive_ssh_target}"
+                            fi
                         fi
-                    fi
 
-                    [[ "$output" != "nagios" ]] && info "uncompressing $first_wal_file to measure its size"
-                    raw_size=$($ARCHIVE_UNCOMPRESS_BIN -c $tmpwal 2>/dev/null| wc -c)
-                    if [[ -z "$raw_size" ]] || [[ "$raw_size" == 0 ]]; then
-                        die "Could not uncompress the WAL to check its size"
-                    fi
+                        [[ "$output" != "nagios" ]] && info "uncompressing $first_wal_file to measure its size"
+                        wal_segsize=$($ARCHIVE_UNCOMPRESS_BIN -c $tmpwal 2>/dev/null| wc -c)
+                        if [[ -z "$wal_segsize" ]] || [[ "$wal_segsize" == 0 ]]; then
+                            die "Could not uncompress the WAL to check its size"
+                        fi
 
-                    rm -f -- $tmpwal
+                        rm -f -- $tmpwal
+                    fi
 
                     # wal_segsize is in bytes, compute the number of segments per log
-                    max_seg=$(( 0xFFFFFFFF / $raw_size ))
-                    segsize=$(( $raw_size / 1048576 ))
-                    [[ "$output" != "nagios" ]] && info "WAL segment size: ${segsize}Mb"
+                    max_seg=$(( 0xFFFFFFFF / $wal_segsize ))
+                    segsize=$(( $wal_segsize / 1048576 ))
+                    [[ "$output" != "nagios" ]] && info "WAL segment size: ${segsize}MB"
                 fi
 
                 [[ "$output" != "nagios" ]] && info "WAL segments per log: $max_seg"
