Issue 130: abort check if backup_timestamp is not available

diff --git a/pitrery b/pitrery
--- a/pitrery
+++ b/pitrery
@@ -3623,6 +3623,9 @@ case $action in
 				else
 					ts=$(ssh -n -- "$backup_ssh_target" "cat -- $(qw "$dir/backup_timestamp")")
 				fi
+				if [ "$?" -ne "0" ]; then
+					die "The backup_timestamp file is missing from all/some directories in the backup directory. Please Fix it."
+				fi
 
 				# The timestamp must be a string of (only) digits, we do arithmetic with it
 				if [[ $ts =~ ^[[:digit:]]+$ ]]; then
@@ -3721,6 +3724,9 @@ case $action in
 					ts=$(< "$dir/backup_timestamp")
 				else
 					ts=$(ssh -n -- "$backup_ssh_target" "cat -- $(qw "$dir/backup_timestamp")")
+				fi
+				if [ "$?" -ne "0" ]; then
+					die "The backup_timestamp file is missing from all/some directories in the backup directory. Please Fix it."
 				fi
 
 				# The timestamp must be a string of (only) digits, we do arithmetic with it
