shellcheck corrections: SC2164,SC2198,SC2006,SC2002

diff --git a/pitrery b/pitrery
--- a/pitrery
+++ b/pitrery
@@ -42,7 +42,7 @@ PRE_BACKUP_COMMAND=
 POST_BACKUP_COMMAND=
 LOG_TIMESTAMP="yes"
 USE_ISO8601_TIMESTAMPS="no"
-PGOWNER=`id -un`
+PGOWNER=$(id -un)
 OVERWRITE="no"
 RESTORE_COMMAND=
 RESTORE_MODE="recovery"
@@ -79,9 +79,9 @@ rsync_opts=""
 usage() {
 	case $1 in
 		list)
-			echo "`basename $0` list - Display information about backups"
+			echo "$(basename $0) list - Display information about backups"
 			echo
-			echo "usage: `basename $0` list [options] [[[user@]host:]/path/to/backups]"
+			echo "usage: $(basename $0) list [options] [[[user@]host:]/path/to/backups]"
 			echo
 			echo "options:"
 			echo "    -v              Display details of the backup"
@@ -91,9 +91,9 @@ usage() {
 			exit ${2:-0}
 			;;
 		backup)
-			echo "`basename $0` backup - Perform a base backup"
+			echo "$(basename $0) backup - Perform a base backup"
 			echo
-			echo "usage: `basename $0` backup [options] [[[user@]host:]/path/to/backups]"
+			echo "usage: $(basename $0) backup [options] [[[user@]host:]/path/to/backups]"
 			echo
 			echo "options:"
 			echo "    -D dir               Path to \$PGDATA"
@@ -116,9 +116,9 @@ usage() {
 			exit ${2:-0}
 			;;
 		restore)
-			echo "`basename $0` restore - Restore a base backup and prepare PITR"
+			echo "$(basename $0) restore - Restore a base backup and prepare PITR"
 			echo
-			echo "usage: `basename $0` restore [options] [[[user@]host:]/path/to/backups]"
+			echo "usage: $(basename $0) restore [options] [[[user@]host:]/path/to/backups]"
 			echo
 			echo " options:"
 			echo "    -D dir               Path to target \$PGDATA"
@@ -141,9 +141,9 @@ usage() {
 			exit ${2:-0}
 			;;
 		purge)
-			echo "`basename $0` purge - Clean old base backups and archived WAL files"
+			echo "$(basename $0) purge - Clean old base backups and archived WAL files"
 			echo
-			echo "usage: `basename $0` purge [options] [[[user@]host:]/path/to/backups]"
+			echo "usage: $(basename $0) purge [options] [[[user@]host:]/path/to/backups]"
 			echo
 			echo "options:"
 			echo "    -m count               Keep this number of backups"
@@ -159,9 +159,9 @@ usage() {
 			exit ${2:-0}
 			;;
 		check)
-			echo "`basename $0` check - Verify configuration and backups integrity"
+			echo "$(basename $0) check - Verify configuration and backups integrity"
 			echo
-			echo "usage: `basename $0` check [options] [[[user@]host:]/path/to/backups]"
+			echo "usage: $(basename $0) check [options] [[[user@]host:]/path/to/backups]"
 			echo
 			echo "options:"
 			echo "    -C conf                Configuration file"
@@ -181,9 +181,9 @@ usage() {
 			exit ${2:-0}
 			;;
 		configure)
-			echo "`basename $0` configure - Create a configuration file from the command line"
+			echo "$(basename $0) configure - Create a configuration file from the command line"
 			echo
-			echo "usage: `basename $0` configure [options] [[user@]host:]/path/to/backups"
+			echo "usage: $(basename $0) configure [options] [[user@]host:]/path/to/backups"
 			echo
 			echo "options:"
 			echo "    -o config_file         Output configuration file"
@@ -209,9 +209,9 @@ usage() {
 			exit ${2:-0}
 			;;
 		help)
-			echo "`basename $0` help - Print help, optionnally for an action"
+			echo "$(basename $0) help - Print help, optionnally for an action"
 			echo
-			echo "usage: `basename $0` help [options] [action]"
+			echo "usage: $(basename $0) help [options] [action]"
 			echo
 			echo "options:"
 			echo "    -?                     Print help"
@@ -221,9 +221,9 @@ usage() {
 	esac
 
 	# Fallback to the main command usage
-	echo "`basename $0` $version - PostgreSQL Point In Time Recovery made easy"
+	echo "$(basename $0) $version - PostgreSQL Point In Time Recovery made easy"
 	echo
-	echo "usage: `basename $0` [options] action [args]"
+	echo "usage: $(basename $0) [options] action [args]"
 	echo
 	echo "options:"
 	echo "    -f file      Path to the configuration file"
@@ -590,7 +590,7 @@ check_and_fix_directory() {
 		fi
 
 		# Check permissions
-		dperms=`stat -c %a -- "$dir" 2>/dev/null` || die "Unable to get permissions of $dir"
+		dperms=$(stat -c %a -- "$dir" 2>/dev/null) || die "Unable to get permissions of $dir"
 
 		if [ "$dperms" != "700" ]; then
 			if [ "$dry_run" != "yes" ]; then
@@ -602,10 +602,10 @@ check_and_fix_directory() {
 
 	if [ "$dry_run" != "yes" ]; then
 		# Check owner
-		downer=`stat -c %U -- "$dir" 2>/dev/null` || die "Unable to get owner of $dir"
+		downer=$(stat -c %U -- "$dir" 2>/dev/null) || die "Unable to get owner of $dir"
 
 		if [ "$downer" != "$PGOWNER" ]; then
-			if [ "`id -u`" = 0 ]; then
+			if [ "$(id -u)" = 0 ]; then
 				info "setting owner of $dir"
 				chown -- "$PGOWNER:" "$dir" || die "could not change owner of $dir to $PGOWNER"
 			else
@@ -846,10 +846,10 @@ output_param() {
 		# interpreting $ starting strings correctly.
 		echo "$v" | grep '^\$' >/dev/null 2>&1
 		if [ $? = 0 ]; then
-			cat "$file" | sed -re "s/^#${param}=.*/${param}=${v//\//\\/}/" > "$tmpfile" ||
+			sed -re "s/^#${param}=.*/${param}=${v//\//\\/}/" "$file" > "$tmpfile" ||
 				error "Cannot change parameter in configuration file"
 		else
-			cat "$file" | sed -re "s/^#${param}=.*/${param}=\"${v//\//\\/}\"/" > "$tmpfile" ||
+			sed -re "s/^#${param}=.*/${param}=\"${v//\//\\/}\"/" "$file" > "$tmpfile" ||
 				error "Cannot change parameter in configuration file"
 		fi
 
@@ -1098,7 +1098,7 @@ case $action in
 
 				list_output_json "directory" "$dir"
 			else
-				echo -ne "$dir\t"
+				echo -ne "$dir\\t"
 			fi
 
 			# Compute the size of full backup
@@ -1114,7 +1114,7 @@ case $action in
 					list_output_text "  space used" "$backup_size"
 					list_output_json "space_used" "$backup_size"
 				else
-					echo -ne "$backup_size\t"
+					echo -ne "$backup_size\\t"
 				fi
 			else
 				error "could not find size of $dir"
@@ -1359,7 +1359,7 @@ case $action in
 		fi
 
 		# Prepare the text will put in the backup_label
-		label_text="pitrery_${version}_`date +%s`"
+		label_text="pitrery_${version}_$(date +%s)"
 
 		# Prepare psql command line. Starting from 9.6 .psqlrc is sourced with
 		# psql -c or -f, so we force -X
@@ -1565,10 +1565,10 @@ case $action in
 			# backup_label that will be archived after pg_stop_backup
 			# completes
 			if (( $pg_version >= 80400 )); then
-				start_backup_label_file=`"${psql_command[@]}" -Atc "select i.file_name ||'.'|| lpad(upper(to_hex(i.file_offset)), 8, '0') || '.backup' from pg_${xlog_or_wal}file_name_offset(pg_start_backup('${label_text}', true)) as i;" $psql_condb`
+				start_backup_label_file=$("${psql_command[@]}" -Atc "select i.file_name ||'.'|| lpad(upper(to_hex(i.file_offset)), 8, '0') || '.backup' from pg_${xlog_or_wal}file_name_offset(pg_start_backup('${label_text}', true)) as i;" $psql_condb)
 				rc=$?
 			else
-				start_backup_label_file=`"${psql_command[@]}" -Atc "select i.file_name ||'.'|| lpad(upper(to_hex(i.file_offset)), 8, '0') || '.backup' from pg_${xlog_or_wal}file_name_offset(pg_start_backup('${label_text}')) as i;" $psql_condb`
+				start_backup_label_file=$("${psql_command[@]}" -Atc "select i.file_name ||'.'|| lpad(upper(to_hex(i.file_offset)), 8, '0') || '.backup' from pg_${xlog_or_wal}file_name_offset(pg_start_backup('${label_text}')) as i;" $psql_condb)
 				rc=$?
 			fi
 
@@ -1611,7 +1611,7 @@ case $action in
 			"tar")
 				# Tar $PGDATA
 				info "backing up PGDATA with tar"
-				was=`pwd`
+				was=$(pwd)
 				if ! cd -- "$PGDATA"; then
 					die_and_hook "could not change current directory to $PGDATA"
 				fi
@@ -1663,7 +1663,7 @@ case $action in
 						fi
 					fi
 				fi
-				cd -- "$was"
+				cd -- "$was" || die_and_hook "$was directory not reachable"
 
 				# Tar the tablespaces
 				while read -r line ; do
@@ -1678,7 +1678,7 @@ case $action in
 
 					# Change directory to the parent directory or the tablespace to be
 					# able to tar only the base directory
-					was=`pwd`
+					was=$(pwd)
 					if ! cd -- "$location"; then
 						die_and_hook "could not change current directory to $location"
 					fi
@@ -1727,7 +1727,7 @@ case $action in
 						fi
 					fi
 
-					cd -- "$was"
+					cd -- "$was" || die_and_hook "$was directory not reachable"
 
 				done < "$tblspc_list"
 				;;
@@ -1941,10 +1941,10 @@ case $action in
 
 		# Ask PostgreSQL where are its configuration file. When they are
 		# outside PGDATA, copy them in the backup
-		_pgdata=`readlink -f -- "$PGDATA"`
+		_pgdata=$(readlink -f -- "$PGDATA")
 
 		while read -r -d '' f; do
-			file=`readlink -f -- "$f"`
+			file=$(readlink -f -- "$f")
 			if [[ ! $file =~ ^"$_pgdata" ]]; then
 				# the file in not inside PGDATA, copy it
 				destdir=$backup_dir/conf
@@ -1990,7 +1990,7 @@ case $action in
 														 "SELECT setting FROM pg_settings WHERE name = '$f';" \
 														 -- "$psql_condb" \
 					|| warn "could not get the list of configuration files from PostgreSQL"
-				printf "\0"
+				printf "\\0"
 			done
 		)
 
@@ -2467,8 +2467,8 @@ case $action in
 			"tar")
 				# pgdata
 				info "extracting PGDATA to $PGDATA"
-				was=`pwd`
-				cd -- "$PGDATA"
+				was=$(pwd)
+				cd -- "$PGDATA" || die_and_hook "$PGDATA directory not reachable"
 				if [ "$backup_local" = "yes" ]; then
 					if [ "$BACKUP_ENCRYPT" = "yes" ]; then
 						"${gpg_command[@]}" -o - "$backup_dir/pgdata.tar.gpg" | tar xf -
@@ -2508,7 +2508,7 @@ case $action in
 						fi
 					fi
 				fi
-				cd -- "$was"
+				cd -- "$was" || die_and_hook "$was directory not reachable"
 				info "extraction of PGDATA successful"
 				;;
 
@@ -2592,7 +2592,7 @@ case $action in
 		fi
 
 		# change owner of PGDATA to the target owner
-		if [ "`id -u`" = 0 ] && [ "`id -un`" != "$PGOWNER" ]; then
+		if [ "$(id -u)" = 0 ] && [ "$(id -un)" != "$PGOWNER" ]; then
 			info "setting owner of PGDATA ($PGDATA)"
 			if ! chown -R -- "$PGOWNER:" "$PGDATA"; then
 				die "could not change owner of PGDATA to $PGOWNER"
@@ -2616,7 +2616,7 @@ case $action in
 
 				# Ensure the new link has the correct owner, the chown -R
 				# issued after extraction will not do it
-				if [ "`id -u`" = 0 ] && [ "`id -un`" != "$PGOWNER" ]; then
+				if [ "$(id -u)" = 0 ] && [ "$(id -un)" != "$PGOWNER" ]; then
 					chown -h -- "$PGOWNER:" "$PGDATA/pg_tblspc/$oid"
 				fi
 			fi
@@ -2625,8 +2625,8 @@ case $action in
 			case $storage in
 				"tar")
 					info "extracting tablespace \"${name}\" to $tbldir"
-					was=`pwd`
-					cd -- "$tbldir"
+					was=$(pwd)
+					cd -- "$tbldir" || die_and_hook "$tbldir directory not reachable"
 					if [ "$backup_local" = "yes" ]; then
 						if [ "$BACKUP_ENCRYPT" = "yes" ]; then
 							"${gpg_command[@]}" -o - "$backup_dir/tblspc/${_name}.tar.gpg" | tar xf -
@@ -2666,7 +2666,7 @@ case $action in
 							fi
 						fi
 					fi
-					cd -- "$was"
+					cd -- "$was" || die_and_hook "$was directory not reachable"
 					info "extraction of tablespace \"${name}\" successful"
 					;;
 
@@ -2694,7 +2694,7 @@ case $action in
 			esac
 
 			# change owner of the tablespace files to the target owner
-			if [ "`id -u`" = 0 ] && [ "`id -un`" != "$PGOWNER" ]; then
+			if [ "$(id -u)" = 0 ] && [ "$(id -un)" != "$PGOWNER" ]; then
 				info "setting owner of tablespace \"$name\" ($tbldir)"
 				if ! chown -R -- "$PGOWNER:" "$tbldir"; then
 					die "could not change owner of tablespace \"$name\" to $PGOWNER"
@@ -2763,7 +2763,7 @@ case $action in
 			if ! ln -sf -- "$PGWAL" "$PGDATA/pg_${xlog_or_wal}"; then
 				die "could not create $PGDATA/pg_${xlog_or_wal} symbolic link"
 			fi
-			if [ "`id -u`" = 0 ] && [ "`id -un`" != "$PGOWNER" ]; then
+			if [ "$(id -u)" = 0 ] && [ "$(id -un)" != "$PGOWNER" ]; then
 				if ! chown -h -- "$PGOWNER:" "$PGDATA/pg_${xlog_or_wal}"; then
 					die "could not change owner of pg_${xlog_or_wal} symbolic link to $PGOWNER"
 				fi
@@ -2780,7 +2780,7 @@ case $action in
 				die "could not set permissions of $PGDATA/pg_${xlog_or_wal} and $PGDATA/pg_${xlog_or_wal}/archive_status"
 			fi
 
-			if [ "`id -u`" = 0 ] && [ "`id -un`" != "$PGOWNER" ]; then
+			if [ "$(id -u)" = 0 ] && [ "$(id -un)" != "$PGOWNER" ]; then
 				if ! chown -R -- "$PGOWNER:" "$PGDATA/pg_${xlog_or_wal}"; then
 					die "could not change owner of $dir to $PGOWNER"
 				fi
@@ -2873,7 +2873,7 @@ case $action in
 
 			# Ensure recovery file as the correct owner so that PostgreSQL can
 			# rename it at the end of the recovery
-			if [ "`id -u`" = 0 ] && [ "`id -un`" != "$PGOWNER" ] && [ -n "$recovery_file" ]; then
+			if [ "$(id -u)" = 0 ] && [ "$(id -un)" != "$PGOWNER" ] && [ -n "$recovery_file" ]; then
 				if ! chown -R -- "$PGOWNER:" "$PGDATA/$recovery_file"; then
 					die "could not change owner of $recovery_file to $PGOWNER"
 				fi
@@ -2906,7 +2906,7 @@ case $action in
 
 			# Ensure signal file as the correct owner so that PostgreSQL can
 			# delete it at the end of the recovery
-			if [ "`id -u`" = 0 ] && [ "`id -un`" != "$PGOWNER" ] && [ -n "$restore_mode_file" ]; then
+			if [ "$(id -u)" = 0 ] && [ "$(id -un)" != "$PGOWNER" ] && [ -n "$restore_mode_file" ]; then
 				if ! chown -R -- "$PGOWNER:" "$PGDATA/$restore_mode_file"; then
 					die "could not change owner of $restore_mode_file to $PGOWNER"
 				fi
@@ -2960,11 +2960,11 @@ case $action in
 			for (( i=0; i<$tspc_count; ++i )); do
 				if [ "${tspc_reloc[$i]}" = "yes" ]; then
 					echo "-- update location of ${tspc_name[$i]} to ${tspc_dir[$i]}" >> "$updsql"
-					printf "UPDATE pg_catalog.pg_tablespace SET spclocation = '%s' WHERE oid = %s;\n" "${tspc_dir[$i]}" "${tspc_oid[$i]}" >> "$updsql"
+					printf "UPDATE pg_catalog.pg_tablespace SET spclocation = '%s' WHERE oid = %s;\\n" "${tspc_dir[$i]}" "${tspc_oid[$i]}" >> "$updsql"
 				fi
 			done
 
-			if [ "`id -u`" = 0 ] && [ "`id -un`" != "$PGOWNER" ]; then
+			if [ "$(id -u)" = 0 ] && [ "$(id -un)" != "$PGOWNER" ]; then
 				chown -- "$PGOWNER:" "$updsql" 2>/dev/null
 			fi
 		fi
@@ -3045,7 +3045,7 @@ case $action in
 		fi
 
 		if [ -f "$replslots_sql" ]; then
-			if [[ $(cat "$replslots_sql"|wc -l) -gt 0 ]]; then
+			if [[ $(wc -l "$replslots_sql"|cut -d' ' -f1) -gt 0 ]]; then
 				info "replication slots defined at the time of the backup can be restored"
 				info "with the SQL commands from:"
 				info "  $replslots_sql"
@@ -3918,7 +3918,7 @@ case $action in
               die "No uncompress command is defined"
 						else
 							[[ "$output" != "nagios" ]] && info "assuming WAL segments are not compressed"
-							wal_segsize=$(cat $tmpwal 2>/dev/null| wc -c)
+							wal_segsize=$(wc -c $tmpwal 2>/dev/null |cut -d' ' -f1)
 							if [[ -z "$wal_segsize" ]] || [[ "$wal_segsize" == 0 ]]; then
 								die "Could not get the size of the WAL segment"
 							fi
@@ -4110,7 +4110,7 @@ case $action in
 		done
 
 		# target directory for backups must be provided
-		if [ -z "${@:$OPTIND:1}" ]; then
+		if [ -z "${*:$OPTIND:1}" ]; then
 			error "missing target backup directory"
 			usage "configure"
 		fi
