restore_xlog: use user@host:path

diff --git a/restore_xlog b/restore_xlog
--- a/restore_xlog
+++ b/restore_xlog
@@ -1,4 +1,4 @@
-#!@BASH@
+#!/bin/bash
 #
 # Copyright 2011-2017 Nicolas Thauvin. All rights reserved.
 #
@@ -23,6 +23,17 @@
 # (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 # THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #
+
+# Default configuration
+SYSLOG="no"
+ARCHIVE_COMPRESS="yes"
+ARCHIVE_UNCOMPRESS_BIN=gunzip
+ARCHIVE_COMPRESS_SUFFIX=gz
+
+CONFIG_DIR="/etc/pitrery"
+CONFIG="pitrery.conf"
+
+
 
 # Apply an extra level of shell quoting to each of the arguments passed.
 # This is necessary for remote-side arguments of ssh (including commands that
@@ -54,44 +65,98 @@ warn() {
 
 # Script help
 usage() {
+    echo "$(basename $0) - Restore a WAL segment"
+    echo
     echo "usage: `basename $0` [options] xlogfile destination"
     echo "options:"
-    echo "    -L             restore local archives"
-    echo "    -C conf        configuration file"
-    echo "    -u username    username for SSH login"
-    echo "    -h hostname    hostname for SSH login"
-    echo "    -d dir         directory containing WALs on host"
-    echo "    -X             do not uncompress"
-    echo "    -c command     uncompression command"
-    echo "    -s suffix      compressed file suffix (ex: gz)"
-    echo "    -S             send messages to syslog"
-    echo "    -f facility    syslog facility"
-    echo "    -t ident       syslog ident"
+    echo "    -C conf                Configuration file"
+    echo "    -a [[user@]host:]/dir  Place to get the archive"
+    echo "    -X                     Do not uncompress"
+    echo "    -c command             Uncompression command"
+    echo "    -s suffix              Compressed file suffix (ex: gz)"
+    echo "    -S                     Send messages to syslog"
+    echo "    -f facility            Syslog facility"
+    echo "    -t ident               Syslog ident"
+    echo "    -T                     Timestamp log messages"
     echo
-    echo "    -T             Timestamp log messages"
-    echo "    -?             print help"
+    echo "    -?                     Print help"
     echo
     exit $1
 }
 
-# Default configuration
-CONFIG=pitr.conf
-CONFIG_DIR=@SYSCONFDIR@
-ARCHIVE_DIR=/var/lib/pgsql/archived_xlog
-ARCHIVE_LOCAL="no"
-SYSLOG="no"
-ARCHIVE_COMPRESS="yes"
-ARCHIVE_UNCOMPRESS_BIN=gunzip
-ARCHIVE_COMPRESS_SUFFIX=gz
+parse_target_uri() {
+    local backup_target=$1
+    local archive_target=$2
+
+    if [ -n "$backup_target" ]; then
+        # Parse the backuptarget into user, host and path
+        backup_user="$(echo $backup_target | grep '@' | cut -d'@' -f1 )"
+        backup_host="$(echo $backup_target | grep ':' | sed -re 's/(.*):(.*)/\1/' | cut -d'@' -f2 )"
+        backup_dir="$(echo $backup_target | sed -re 's/(.*):(.*)/\2/')"
+       
+    else
+        # Fallback to the values from the configuration file
+        [ -n "$BACKUP_USER" ] && backup_user=$BACKUP_USER
+        [ -n "$BACKUP_HOST" ] && backup_host=$BACKUP_HOST
+        [ -n "$BACKUP_DIR" ] && backup_dir=$BACKUP_DIR
+    fi
+
+    [ -n "$backup_dir" ] || error "missing backup directory"
+    
+    # Deduce if backup is local
+    if [ -z "$backup_host" ]; then
+        backup_local="yes"
+    else
+        backup_local="no"
+
+        # Wrap IPv6 addresses with brackets
+        echo $backup_host | grep -qi '^[0123456789abcdef:]*:[0123456789abcdef:]*$' && backup_host="[${backup_host}]"
+
+        # Add a shortcut for ssh/rsync commands
+        backup_ssh_target=${backup_user:+$backup_user@}$backup_host
+    fi
+    
+    # Parse archive target the same way
+    if [ -n "$archive_target" ]; then
+        archive_user="$(echo $archive_target | grep '@' | cut -d'@' -f1 )"
+        archive_host="$(echo $archive_target | grep ':' | sed -re 's/(.*):(.*)/\1/' | cut -d'@' -f2 )"
+        archive_dir="$(echo $archive_target | sed -re 's/(.*):(.*)/\2/')"
+    else
+        # Fallback to the values of the configuration file. When the
+        # path is not provided in the config file, fallback to backup values
+        if [ -n "$ARCHIVE_DIR" ]; then
+            [ -n "$ARCHIVE_USER" ] && archive_user=$ARCHIVE_USER
+            [ -n "$ARCHIVE_HOST" ] && archive_host=$ARCHIVE_HOST
+            archive_dir=$ARCHIVE_DIR
+        else
+            archive_user="$backup_user"
+            archive_host="$backup_host"
+            archive_dir="$backup_dir/archived_xlog"
+        fi
+    fi
+
+    # Deduce if archives are local
+    if [ -z "$archive_host" ]; then
+	archive_local="yes"
+    else
+	archive_local="no"
+
+        # Wrap IPv6 addresses with brackets
+        echo $archive_host | grep -qi '^[0123456789abcdef:]*:[0123456789abcdef:]*$' && archive_host="[${archive_host}]"
+
+        # Add a shortcut for ssh/rsync commands
+        archive_ssh_target=${archive_user:+$archive_user@}$archive_host
+    fi
+
+    [ -n "$archive_dir" ] || error "missing archive directory"
+
+}
 
 # CLI processing
-while getopts "LC:u:h:d:Xc:s:Sf:t:?" opt; do
+while getopts "C:a:Xc:s:Sf:t:?" opt; do
     case $opt in
-	L) CLI_ARCHIVE_LOCAL="yes";;
 	C) CONFIG=$OPTARG;;
-	u) CLI_ARCHIVE_USER=$OPTARG;;
-	h) CLI_ARCHIVE_HOST=$OPTARG;;
-	d) CLI_ARCHIVE_DIR=$OPTARG;;
+        a) archive_path="$OPTARG";;
 	X) CLI_ARCHIVE_COMPRESS="no";;
 	c) CLI_ARCHIVE_UNCOMPRESS_BIN=$OPTARG;;
 	s) CLI_ARCHIVE_COMPRESS_SUFFIX=$OPTARG;;
@@ -114,28 +179,9 @@ fi
 # Load configuration file
 if [ -f "$CONFIG" ]; then
     . "$CONFIG"
-
-    # Check for renamed parameters between versions
-    if [ -n "$UNCOMPRESS_BIN" ] && [ -z "$CLI_ARCHIVE_UNCOMPRESS_BIN" ]; then
-	ARCHIVE_UNCOMPRESS_BIN=$UNCOMPRESS_BIN
-	warn "restore_xlog: UNCOMPRESS_BIN is deprecated. please use ARCHIVE_UNCOMPRESS_BIN."
-    fi
-    if [ -n "$COMPRESS_SUFFIX" ] && [ -z "$CLI_ARCHIVE_COMPRESS_SUFFIX" ]; then
-	ARCHIVE_COMPRESS_SUFFIX=$COMPRESS_SUFFIX
-	warn "restore_xlog: COMPRESS_SUFFIX is deprecated. please use ARCHIVE_COMPRESS_SUFFIX."
-    fi
 fi
 
 # Override configuration with cli options
-if [ -n "$CLI_ARCHIVE_HOST" ]; then
-    ARCHIVE_HOST=$CLI_ARCHIVE_HOST
-    [ -n "$CLI_ARCHIVE_USER" ] && ARCHIVE_USER=$CLI_ARCHIVE_USER
-    # When a host storing the archives is given for local to no, as it
-    # can come from the configuration file
-    ARCHIVE_LOCAL="no"
-fi
-[ -n "$CLI_ARCHIVE_LOCAL" ] && ARCHIVE_LOCAL=$CLI_ARCHIVE_LOCAL
-[ -n "$CLI_ARCHIVE_DIR" ] && ARCHIVE_DIR=$CLI_ARCHIVE_DIR
 [ -n "$CLI_ARCHIVE_COMPRESS" ] && ARCHIVE_COMPRESS=$CLI_ARCHIVE_COMPRESS
 [ -n "$CLI_ARCHIVE_UNCOMPRESS_BIN" ] && ARCHIVE_UNCOMPRESS_BIN=$CLI_ARCHIVE_UNCOMPRESS_BIN
 [ -n "$CLI_ARCHIVE_COMPRESS_SUFFIX" ] && ARCHIVE_COMPRESS_SUFFIX=$CLI_ARCHIVE_COMPRESS_SUFFIX
@@ -153,6 +199,8 @@ if [ "$SYSLOG" = "yes" ]; then
     exec 2> >(logger -t "$SYSLOG_IDENT" -p "${SYSLOG_FACILITY}.err")
 fi
 
+parse_target_uri "" "$archive_path"
+
 # Check input: the name of the xlog file (%f) is needed as well has the target path (%p)
 # PostgreSQL gives those two when executing restore_command
 xlog=${@:$OPTIND:1}
@@ -160,15 +208,6 @@ target_path=${@:$(($OPTIND+1)):1}
 
 if [ -z "$xlog" ] || [ -z "$target_path" ]; then
     error "missing xlog filename and/or target path. Please use %f and %p in restore_command"
-fi
-
-# Check if we have enough information on where to get the file
-if [ "$ARCHIVE_LOCAL" != "yes" ] && [ -z "$ARCHIVE_HOST" ]; then
-    error "Could not find where to get the file from (local or ssh?)"
-fi
-
-if [ "$ARCHIVE_LOCAL" = "yes" ] && [ -n "$ARCHIVE_HOST" ]; then
-    error "ARCHIVE_LOCAL and ARCHIVE_HOST are set, it can't be both"
 fi
 
 # the filename to retrieve depends on compression
@@ -181,20 +220,17 @@ else
 fi
 
 # Get the file: use cp when the file is on localhost, scp otherwise
-if [ "$ARCHIVE_LOCAL" = "yes" ]; then
-    if [ -f "$ARCHIVE_DIR/$xlog_file" ]; then
-	if ! cp -- "$ARCHIVE_DIR/$xlog_file" "$target_file"; then
-	    error "could not copy $ARCHIVE_DIR/$xlog_file to $target_file"
+if [ "$archive_local" = "yes" ]; then
+    if [ -f "$archive_dir/$xlog_file" ]; then
+	if ! cp -- "$archive_dir/$xlog_file" "$target_file"; then
+	    error "could not copy $archive_dir/$xlog_file to $target_file"
 	fi
     else
-	error "could not find $ARCHIVE_DIR/$xlog_file"
+	error "could not find $archive_dir/$xlog_file"
     fi
 else
-    # check if we have a IPv6, and put brackets for scp
-    echo $ARCHIVE_HOST | grep -qi '^[0123456789abcdef:]*:[0123456789abcdef:]*$' && ARCHIVE_HOST="[${ARCHIVE_HOST}]"
-
-    if ! scp -- "${ARCHIVE_USER:+$ARCHIVE_USER@}$ARCHIVE_HOST:$(qw "$ARCHIVE_DIR/$xlog_file")" "$target_file" >/dev/null; then
-	error "could not copy $ARCHIVE_HOST:$ARCHIVE_DIR/$xlog_file to $target_file"
+    if ! scp -- "${archive_ssh_target}:$(qw "$archive_dir/$xlog_file")" "$target_file" >/dev/null; then
+	die "could not copy ${archive_host}:$archive_dir/$xlog_file to $target_file"
     fi
 fi
 
